import "server-only";

export const DEMO_SLUG = "demo-kitchen";
export const DEMO_SEED_REFERENCE = "SCOPELOCK-DEMO-KITCHEN-001";
export const DEMO_CONTACT_NAME = "Baker & Co";
export const DEMO_CONTACT_EMAIL = "demo-baker@scopelock.local";
export const DEMO_MARKER = "SCOPELOCK-DEMO";

export type SeedStepId =
  | "xeroConnected"
  | "salesAccount"
  | "contact"
  | "item:LED-PACK"
  | "item:SOCKET-MOVE"
  | "item:HANDLE-BLACK"
  | "item:PAINT-HALL"
  | "item:EXTRA-CAB"
  | "quote"
  | "projectLink";

export type SeedStepStatus = "CREATED" | "FOUND" | "UPDATED" | "FAILED" | "MANUAL_ACTION_REQUIRED";

export interface SeedStepResult {
  step: SeedStepId;
  label: string;
  status: SeedStepStatus;
  message?: string;
  xeroId?: string;
}

export interface SeedResult {
  steps: SeedStepResult[];
  success: boolean;
}

export interface DemoItemSpec {
  code: string;
  name: string;
  salesDescription: string;
  salesUnitPrice: number;
}

// Prices are the source of truth for any future variation pricing — never
// generated by an LLM. Kept alongside the seed reference constants so the
// demo script and any future scope-comparison code both read from here.
export const DEMO_ITEMS: DemoItemSpec[] = [
  {
    code: "LED-PACK",
    name: "Under-cabinet LED lighting package",
    salesDescription: "Supply and installation of under-cabinet LED lighting",
    salesUnitPrice: 240,
  },
  {
    code: "SOCKET-MOVE",
    name: "Relocate electrical socket",
    salesDescription: "Relocation of one electrical socket",
    salesUnitPrice: 180,
  },
  {
    code: "HANDLE-BLACK",
    name: "Matte-black cabinet handles",
    salesDescription: "Supply and installation of matte-black cabinet handles",
    salesUnitPrice: 120,
  },
  {
    code: "PAINT-HALL",
    name: "Paint hallway",
    salesDescription: "Prepare and paint hallway walls",
    salesUnitPrice: 450,
  },
  {
    code: "EXTRA-CAB",
    name: "Additional kitchen cabinet",
    salesDescription: "Supply and installation of one additional kitchen cabinet",
    salesUnitPrice: 320,
  },
];

export interface DemoQuoteLineSpec {
  description: string;
  quantity: number;
  unitAmount: number;
  itemCode?: string;
}

// Wording is deliberately explicit — Phase 3 compares client requests
// against this text, so vague phrasing here would break that comparison.
// Totals to exactly £8,400 (see PHASE2_DEMO_SETUP.md for the breakdown).
export const DEMO_QUOTE_LINES: DemoQuoteLineSpec[] = [
  { description: "Remove existing kitchen units", quantity: 1, unitAmount: 600 },
  { description: "Supply and install new cabinets", quantity: 1, unitAmount: 3800 },
  { description: "Install oak worktop", quantity: 1, unitAmount: 1400 },
  { description: "Standard ceiling lighting", quantity: 1, unitAmount: 350 },
  { description: "Install matte-black cabinet handles", quantity: 1, unitAmount: 120, itemCode: "HANDLE-BLACK" },
  { description: "Electrical work at existing socket locations", quantity: 1, unitAmount: 2130 },
];

export const DEMO_QUOTE_TITLE = "Kitchen Refurbishment";

// Shown only as a preview card in Phase 2 — never analysed until Phase 3.
export const DEMO_NEXT_PHASE_MESSAGE =
  "The kitchen looks great. Could you also add LED lights underneath the cabinets and move the two sockets beside the fridge? Please make sure the handles are matte black like we agreed.";
